# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tblut/gameprogramming

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tblut/gameprogramming

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tblut/gameprogramming/CMakeFiles /home/tblut/gameprogramming/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tblut/gameprogramming/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lib1

# Build rule for target.
lib1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib1
.PHONY : lib1

# fast build rule for target.
lib1/fast:
	$(MAKE) -f CMakeFiles/lib1.dir/build.make CMakeFiles/lib1.dir/build
.PHONY : lib1/fast

#=============================================================================
# Target rules for targets named lib2

# Build rule for target.
lib2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib2
.PHONY : lib2

# fast build rule for target.
lib2/fast:
	$(MAKE) -f CMakeFiles/lib2.dir/build.make CMakeFiles/lib2.dir/build
.PHONY : lib2/fast

#=============================================================================
# Target rules for targets named lib3

# Build rule for target.
lib3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib3
.PHONY : lib3

# fast build rule for target.
lib3/fast:
	$(MAKE) -f CMakeFiles/lib3.dir/build.make CMakeFiles/lib3.dir/build
.PHONY : lib3/fast

#=============================================================================
# Target rules for targets named tankwars

# Build rule for target.
tankwars: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tankwars
.PHONY : tankwars

# fast build rule for target.
tankwars/fast:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/build
.PHONY : tankwars/fast

Source/Game/Camera.o: Source/Game/Camera.cpp.o

.PHONY : Source/Game/Camera.o

# target to build an object file
Source/Game/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Camera.cpp.o
.PHONY : Source/Game/Camera.cpp.o

Source/Game/Camera.i: Source/Game/Camera.cpp.i

.PHONY : Source/Game/Camera.i

# target to preprocess a source file
Source/Game/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Camera.cpp.i
.PHONY : Source/Game/Camera.cpp.i

Source/Game/Camera.s: Source/Game/Camera.cpp.s

.PHONY : Source/Game/Camera.s

# target to generate assembly for a file
Source/Game/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Camera.cpp.s
.PHONY : Source/Game/Camera.cpp.s

Source/Game/ExplosionHandling.o: Source/Game/ExplosionHandling.cpp.o

.PHONY : Source/Game/ExplosionHandling.o

# target to build an object file
Source/Game/ExplosionHandling.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/ExplosionHandling.cpp.o
.PHONY : Source/Game/ExplosionHandling.cpp.o

Source/Game/ExplosionHandling.i: Source/Game/ExplosionHandling.cpp.i

.PHONY : Source/Game/ExplosionHandling.i

# target to preprocess a source file
Source/Game/ExplosionHandling.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/ExplosionHandling.cpp.i
.PHONY : Source/Game/ExplosionHandling.cpp.i

Source/Game/ExplosionHandling.s: Source/Game/ExplosionHandling.cpp.s

.PHONY : Source/Game/ExplosionHandling.s

# target to generate assembly for a file
Source/Game/ExplosionHandling.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/ExplosionHandling.cpp.s
.PHONY : Source/Game/ExplosionHandling.cpp.s

Source/Game/GLTools.o: Source/Game/GLTools.cpp.o

.PHONY : Source/Game/GLTools.o

# target to build an object file
Source/Game/GLTools.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/GLTools.cpp.o
.PHONY : Source/Game/GLTools.cpp.o

Source/Game/GLTools.i: Source/Game/GLTools.cpp.i

.PHONY : Source/Game/GLTools.i

# target to preprocess a source file
Source/Game/GLTools.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/GLTools.cpp.i
.PHONY : Source/Game/GLTools.cpp.i

Source/Game/GLTools.s: Source/Game/GLTools.cpp.s

.PHONY : Source/Game/GLTools.s

# target to generate assembly for a file
Source/Game/GLTools.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/GLTools.cpp.s
.PHONY : Source/Game/GLTools.cpp.s

Source/Game/Game.o: Source/Game/Game.cpp.o

.PHONY : Source/Game/Game.o

# target to build an object file
Source/Game/Game.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Game.cpp.o
.PHONY : Source/Game/Game.cpp.o

Source/Game/Game.i: Source/Game/Game.cpp.i

.PHONY : Source/Game/Game.i

# target to preprocess a source file
Source/Game/Game.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Game.cpp.i
.PHONY : Source/Game/Game.cpp.i

Source/Game/Game.s: Source/Game/Game.cpp.s

.PHONY : Source/Game/Game.s

# target to generate assembly for a file
Source/Game/Game.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Game.cpp.s
.PHONY : Source/Game/Game.cpp.s

Source/Game/Image.o: Source/Game/Image.cpp.o

.PHONY : Source/Game/Image.o

# target to build an object file
Source/Game/Image.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Image.cpp.o
.PHONY : Source/Game/Image.cpp.o

Source/Game/Image.i: Source/Game/Image.cpp.i

.PHONY : Source/Game/Image.i

# target to preprocess a source file
Source/Game/Image.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Image.cpp.i
.PHONY : Source/Game/Image.cpp.i

Source/Game/Image.s: Source/Game/Image.cpp.s

.PHONY : Source/Game/Image.s

# target to generate assembly for a file
Source/Game/Image.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Image.cpp.s
.PHONY : Source/Game/Image.cpp.s

Source/Game/Keyboard.o: Source/Game/Keyboard.cpp.o

.PHONY : Source/Game/Keyboard.o

# target to build an object file
Source/Game/Keyboard.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Keyboard.cpp.o
.PHONY : Source/Game/Keyboard.cpp.o

Source/Game/Keyboard.i: Source/Game/Keyboard.cpp.i

.PHONY : Source/Game/Keyboard.i

# target to preprocess a source file
Source/Game/Keyboard.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Keyboard.cpp.i
.PHONY : Source/Game/Keyboard.cpp.i

Source/Game/Keyboard.s: Source/Game/Keyboard.cpp.s

.PHONY : Source/Game/Keyboard.s

# target to generate assembly for a file
Source/Game/Keyboard.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Keyboard.cpp.s
.PHONY : Source/Game/Keyboard.cpp.s

Source/Game/Main.o: Source/Game/Main.cpp.o

.PHONY : Source/Game/Main.o

# target to build an object file
Source/Game/Main.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Main.cpp.o
.PHONY : Source/Game/Main.cpp.o

Source/Game/Main.i: Source/Game/Main.cpp.i

.PHONY : Source/Game/Main.i

# target to preprocess a source file
Source/Game/Main.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Main.cpp.i
.PHONY : Source/Game/Main.cpp.i

Source/Game/Main.s: Source/Game/Main.cpp.s

.PHONY : Source/Game/Main.s

# target to generate assembly for a file
Source/Game/Main.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Main.cpp.s
.PHONY : Source/Game/Main.cpp.s

Source/Game/MarchingCubes.o: Source/Game/MarchingCubes.cpp.o

.PHONY : Source/Game/MarchingCubes.o

# target to build an object file
Source/Game/MarchingCubes.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/MarchingCubes.cpp.o
.PHONY : Source/Game/MarchingCubes.cpp.o

Source/Game/MarchingCubes.i: Source/Game/MarchingCubes.cpp.i

.PHONY : Source/Game/MarchingCubes.i

# target to preprocess a source file
Source/Game/MarchingCubes.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/MarchingCubes.cpp.i
.PHONY : Source/Game/MarchingCubes.cpp.i

Source/Game/MarchingCubes.s: Source/Game/MarchingCubes.cpp.s

.PHONY : Source/Game/MarchingCubes.s

# target to generate assembly for a file
Source/Game/MarchingCubes.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/MarchingCubes.cpp.s
.PHONY : Source/Game/MarchingCubes.cpp.s

Source/Game/Mesh.o: Source/Game/Mesh.cpp.o

.PHONY : Source/Game/Mesh.o

# target to build an object file
Source/Game/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Mesh.cpp.o
.PHONY : Source/Game/Mesh.cpp.o

Source/Game/Mesh.i: Source/Game/Mesh.cpp.i

.PHONY : Source/Game/Mesh.i

# target to preprocess a source file
Source/Game/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Mesh.cpp.i
.PHONY : Source/Game/Mesh.cpp.i

Source/Game/Mesh.s: Source/Game/Mesh.cpp.s

.PHONY : Source/Game/Mesh.s

# target to generate assembly for a file
Source/Game/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Mesh.cpp.s
.PHONY : Source/Game/Mesh.cpp.s

Source/Game/MeshInstance.o: Source/Game/MeshInstance.cpp.o

.PHONY : Source/Game/MeshInstance.o

# target to build an object file
Source/Game/MeshInstance.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/MeshInstance.cpp.o
.PHONY : Source/Game/MeshInstance.cpp.o

Source/Game/MeshInstance.i: Source/Game/MeshInstance.cpp.i

.PHONY : Source/Game/MeshInstance.i

# target to preprocess a source file
Source/Game/MeshInstance.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/MeshInstance.cpp.i
.PHONY : Source/Game/MeshInstance.cpp.i

Source/Game/MeshInstance.s: Source/Game/MeshInstance.cpp.s

.PHONY : Source/Game/MeshInstance.s

# target to generate assembly for a file
Source/Game/MeshInstance.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/MeshInstance.cpp.s
.PHONY : Source/Game/MeshInstance.cpp.s

Source/Game/MeshTools.o: Source/Game/MeshTools.cpp.o

.PHONY : Source/Game/MeshTools.o

# target to build an object file
Source/Game/MeshTools.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/MeshTools.cpp.o
.PHONY : Source/Game/MeshTools.cpp.o

Source/Game/MeshTools.i: Source/Game/MeshTools.cpp.i

.PHONY : Source/Game/MeshTools.i

# target to preprocess a source file
Source/Game/MeshTools.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/MeshTools.cpp.i
.PHONY : Source/Game/MeshTools.cpp.i

Source/Game/MeshTools.s: Source/Game/MeshTools.cpp.s

.PHONY : Source/Game/MeshTools.s

# target to generate assembly for a file
Source/Game/MeshTools.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/MeshTools.cpp.s
.PHONY : Source/Game/MeshTools.cpp.s

Source/Game/Physics.o: Source/Game/Physics.cpp.o

.PHONY : Source/Game/Physics.o

# target to build an object file
Source/Game/Physics.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Physics.cpp.o
.PHONY : Source/Game/Physics.cpp.o

Source/Game/Physics.i: Source/Game/Physics.cpp.i

.PHONY : Source/Game/Physics.i

# target to preprocess a source file
Source/Game/Physics.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Physics.cpp.i
.PHONY : Source/Game/Physics.cpp.i

Source/Game/Physics.s: Source/Game/Physics.cpp.s

.PHONY : Source/Game/Physics.s

# target to generate assembly for a file
Source/Game/Physics.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Physics.cpp.s
.PHONY : Source/Game/Physics.cpp.s

Source/Game/Renderer.o: Source/Game/Renderer.cpp.o

.PHONY : Source/Game/Renderer.o

# target to build an object file
Source/Game/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Renderer.cpp.o
.PHONY : Source/Game/Renderer.cpp.o

Source/Game/Renderer.i: Source/Game/Renderer.cpp.i

.PHONY : Source/Game/Renderer.i

# target to preprocess a source file
Source/Game/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Renderer.cpp.i
.PHONY : Source/Game/Renderer.cpp.i

Source/Game/Renderer.s: Source/Game/Renderer.cpp.s

.PHONY : Source/Game/Renderer.s

# target to generate assembly for a file
Source/Game/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Renderer.cpp.s
.PHONY : Source/Game/Renderer.cpp.s

Source/Game/Tank.o: Source/Game/Tank.cpp.o

.PHONY : Source/Game/Tank.o

# target to build an object file
Source/Game/Tank.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Tank.cpp.o
.PHONY : Source/Game/Tank.cpp.o

Source/Game/Tank.i: Source/Game/Tank.cpp.i

.PHONY : Source/Game/Tank.i

# target to preprocess a source file
Source/Game/Tank.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Tank.cpp.i
.PHONY : Source/Game/Tank.cpp.i

Source/Game/Tank.s: Source/Game/Tank.cpp.s

.PHONY : Source/Game/Tank.s

# target to generate assembly for a file
Source/Game/Tank.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Tank.cpp.s
.PHONY : Source/Game/Tank.cpp.s

Source/Game/Terrain.o: Source/Game/Terrain.cpp.o

.PHONY : Source/Game/Terrain.o

# target to build an object file
Source/Game/Terrain.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Terrain.cpp.o
.PHONY : Source/Game/Terrain.cpp.o

Source/Game/Terrain.i: Source/Game/Terrain.cpp.i

.PHONY : Source/Game/Terrain.i

# target to preprocess a source file
Source/Game/Terrain.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Terrain.cpp.i
.PHONY : Source/Game/Terrain.cpp.i

Source/Game/Terrain.s: Source/Game/Terrain.cpp.s

.PHONY : Source/Game/Terrain.s

# target to generate assembly for a file
Source/Game/Terrain.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Terrain.cpp.s
.PHONY : Source/Game/Terrain.cpp.s

Source/Game/VoxelChunk.o: Source/Game/VoxelChunk.cpp.o

.PHONY : Source/Game/VoxelChunk.o

# target to build an object file
Source/Game/VoxelChunk.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/VoxelChunk.cpp.o
.PHONY : Source/Game/VoxelChunk.cpp.o

Source/Game/VoxelChunk.i: Source/Game/VoxelChunk.cpp.i

.PHONY : Source/Game/VoxelChunk.i

# target to preprocess a source file
Source/Game/VoxelChunk.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/VoxelChunk.cpp.i
.PHONY : Source/Game/VoxelChunk.cpp.i

Source/Game/VoxelChunk.s: Source/Game/VoxelChunk.cpp.s

.PHONY : Source/Game/VoxelChunk.s

# target to generate assembly for a file
Source/Game/VoxelChunk.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/VoxelChunk.cpp.s
.PHONY : Source/Game/VoxelChunk.cpp.s

Source/Game/VoxelTerrain.o: Source/Game/VoxelTerrain.cpp.o

.PHONY : Source/Game/VoxelTerrain.o

# target to build an object file
Source/Game/VoxelTerrain.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/VoxelTerrain.cpp.o
.PHONY : Source/Game/VoxelTerrain.cpp.o

Source/Game/VoxelTerrain.i: Source/Game/VoxelTerrain.cpp.i

.PHONY : Source/Game/VoxelTerrain.i

# target to preprocess a source file
Source/Game/VoxelTerrain.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/VoxelTerrain.cpp.i
.PHONY : Source/Game/VoxelTerrain.cpp.i

Source/Game/VoxelTerrain.s: Source/Game/VoxelTerrain.cpp.s

.PHONY : Source/Game/VoxelTerrain.s

# target to generate assembly for a file
Source/Game/VoxelTerrain.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/VoxelTerrain.cpp.s
.PHONY : Source/Game/VoxelTerrain.cpp.s

Source/Game/Wavefront.o: Source/Game/Wavefront.cpp.o

.PHONY : Source/Game/Wavefront.o

# target to build an object file
Source/Game/Wavefront.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Wavefront.cpp.o
.PHONY : Source/Game/Wavefront.cpp.o

Source/Game/Wavefront.i: Source/Game/Wavefront.cpp.i

.PHONY : Source/Game/Wavefront.i

# target to preprocess a source file
Source/Game/Wavefront.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Wavefront.cpp.i
.PHONY : Source/Game/Wavefront.cpp.i

Source/Game/Wavefront.s: Source/Game/Wavefront.cpp.s

.PHONY : Source/Game/Wavefront.s

# target to generate assembly for a file
Source/Game/Wavefront.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/Wavefront.cpp.s
.PHONY : Source/Game/Wavefront.cpp.s

Source/Game/stb_image.o: Source/Game/stb_image.cpp.o

.PHONY : Source/Game/stb_image.o

# target to build an object file
Source/Game/stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/stb_image.cpp.o
.PHONY : Source/Game/stb_image.cpp.o

Source/Game/stb_image.i: Source/Game/stb_image.cpp.i

.PHONY : Source/Game/stb_image.i

# target to preprocess a source file
Source/Game/stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/stb_image.cpp.i
.PHONY : Source/Game/stb_image.cpp.i

Source/Game/stb_image.s: Source/Game/stb_image.cpp.s

.PHONY : Source/Game/stb_image.s

# target to generate assembly for a file
Source/Game/stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/tankwars.dir/build.make CMakeFiles/tankwars.dir/Source/Game/stb_image.cpp.s
.PHONY : Source/Game/stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tankwars"
	@echo "... lib3"
	@echo "... lib2"
	@echo "... lib1"
	@echo "... Source/Game/Camera.o"
	@echo "... Source/Game/Camera.i"
	@echo "... Source/Game/Camera.s"
	@echo "... Source/Game/ExplosionHandling.o"
	@echo "... Source/Game/ExplosionHandling.i"
	@echo "... Source/Game/ExplosionHandling.s"
	@echo "... Source/Game/GLTools.o"
	@echo "... Source/Game/GLTools.i"
	@echo "... Source/Game/GLTools.s"
	@echo "... Source/Game/Game.o"
	@echo "... Source/Game/Game.i"
	@echo "... Source/Game/Game.s"
	@echo "... Source/Game/Image.o"
	@echo "... Source/Game/Image.i"
	@echo "... Source/Game/Image.s"
	@echo "... Source/Game/Keyboard.o"
	@echo "... Source/Game/Keyboard.i"
	@echo "... Source/Game/Keyboard.s"
	@echo "... Source/Game/Main.o"
	@echo "... Source/Game/Main.i"
	@echo "... Source/Game/Main.s"
	@echo "... Source/Game/MarchingCubes.o"
	@echo "... Source/Game/MarchingCubes.i"
	@echo "... Source/Game/MarchingCubes.s"
	@echo "... Source/Game/Mesh.o"
	@echo "... Source/Game/Mesh.i"
	@echo "... Source/Game/Mesh.s"
	@echo "... Source/Game/MeshInstance.o"
	@echo "... Source/Game/MeshInstance.i"
	@echo "... Source/Game/MeshInstance.s"
	@echo "... Source/Game/MeshTools.o"
	@echo "... Source/Game/MeshTools.i"
	@echo "... Source/Game/MeshTools.s"
	@echo "... Source/Game/Physics.o"
	@echo "... Source/Game/Physics.i"
	@echo "... Source/Game/Physics.s"
	@echo "... Source/Game/Renderer.o"
	@echo "... Source/Game/Renderer.i"
	@echo "... Source/Game/Renderer.s"
	@echo "... Source/Game/Tank.o"
	@echo "... Source/Game/Tank.i"
	@echo "... Source/Game/Tank.s"
	@echo "... Source/Game/Terrain.o"
	@echo "... Source/Game/Terrain.i"
	@echo "... Source/Game/Terrain.s"
	@echo "... Source/Game/VoxelChunk.o"
	@echo "... Source/Game/VoxelChunk.i"
	@echo "... Source/Game/VoxelChunk.s"
	@echo "... Source/Game/VoxelTerrain.o"
	@echo "... Source/Game/VoxelTerrain.i"
	@echo "... Source/Game/VoxelTerrain.s"
	@echo "... Source/Game/Wavefront.o"
	@echo "... Source/Game/Wavefront.i"
	@echo "... Source/Game/Wavefront.s"
	@echo "... Source/Game/stb_image.o"
	@echo "... Source/Game/stb_image.i"
	@echo "... Source/Game/stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

